import {
  Mail,
  BriefcaseBusiness,
  Building,
  MessageCircle,
  Clock3,
} from "lucide-react";


export default function Contact() {
  return (
    <div className="w-screen relative min-h-screen bg-black">
      <div
        className="max-w-7xl mx-auto px-6 py-24 space-y-20"
        id="contact-view-container"
      >
        <section
          className="text-center max-w-3xl mx-auto space-y-4"
          id="contact-header"
        >
          <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white font-display">
            Let's Build the Future
          </h2>

          <p className="text-[#c2c6d6] text-sm md:text-base leading-relaxed">
            Ready to deploy Next Frontier digital assets? Submit your
            specifications to receive a customized Solutions Proposal instantly
            generated by our engineering matrices.
          </p>
        </section>

        <section
          className="grid grid-cols-1 lg:grid-cols-2 gap-8"
          id="contact-content"
        >
          <div className="border border-white rounded-3xl min-h-[550px] p-8 text-white">
            <div className="space-y-4 text-center">
              <h3 className="text-2xl font-bold text-white ">
                Communication Channels
              </h3>

              <p className="text-[#c2c6d6] leading-relaxed">
                We work with startups, businesses, and enterprises worldwide.
              </p>
            </div>

            <div className="my-8 h-px bg-white/80 " />

            {/* <div className="flex gap-4">
              <Mail className="w-5 h-5 text-purple-400 mt-1 shrink-0" />
              <div>
                <h4 className="font-semibold text-white">Earendel123@gmail.com</h4>
                <p className="text-sm text-[#c2c6d6]">
                  Primary communication for project discussions.
                </p>
              </div>
            </div> */}

            <div className="space-y-5">
  <div className="flex gap-4">
    <Mail className="w-5 h-5 text-purple-400 mt-1 shrink-0" />
    <div>
      <h4 className="font-semibold text-white">Email</h4>
      <p className="text-sm text-[#c2c6d6]">
        Primary communication for project discussions.
      </p>
    </div>
  </div>

  <div className="flex gap-4">
    <BriefcaseBusiness className="w-5 h-5 text-purple-400 mt-1 shrink-0" />
    <div>
      <h4 className="font-semibold text-white">LinkedIn</h4>
      <p className="text-sm text-[#c2c6d6]">
        Strategic collaborations, networking, and partnership opportunities.
      </p>
    </div>
  </div>

  <div className="flex gap-4">
    <Building className="w-5 h-5 text-purple-400 mt-1 shrink-0" />
    <div>
      <h4 className="font-semibold text-white">Github Organization</h4>
      <p className="text-sm text-[#c2c6d6]">
        Corporate inquiries, enterprise engagements, and company relations.
      </p>
    </div>
  </div>

  <div className="flex gap-4">
    <MessageCircle className="w-5 h-5 text-purple-400 mt-1 shrink-0" />
    <div>
      <h4 className="font-semibold text-white">WhatsApp</h4>
      <p className="text-sm text-[#c2c6d6]">
        Quick consultations and urgent inquiries.
      </p>
    </div>
  </div>
</div>

          </div>

          <div className="border border-white rounded-3xl min-h-[550px] p-8  text-white">
            Consultation Form Placeholder
          </div>
        </section>

        <section id="faq">
          <div className="border border-white rounded-3xl min-h-[400px] p-8 max-w-5xl mx-auto">
            FAQ Placeholder
          </div>
        </section>

        <section id="cta">
          <div className="border border-white rounded-3xl min-h-[250px] p-12 flex items-center justify-center max-w-5xl mx-auto">
            CTA Placeholder
          </div>
        </section>
      </div>
    </div>
  );
}
