

export default function Contact() {
  return (
    <div className="w-screen relative h-screen flex items-center justify-center bg-linear-to-r from-purple-900 to-black">
      <div className="space-y-16 pb-16" id="contact-view-container">
        <section className="text-center max-w-3xl mx-auto space-y-4 pt-8" id="contact-header">
          <div>
            <h2 className="text-3xl sm:text-4.5xl font-extrabold tracking-tight text-white font-display">
              Let's Build Something Great Together
            </h2>
            <p className="text-[#c2c6d6] text-sm md:text-base leading-relaxed">
            Ready to deploy Next Frontier digital assets? Submit your specifications to receive a customized Solutions Proposal instantly generated by our engineering matrices.
            </p>
          </div>
        </section>

       
      </div>

      
    </div>
  );
}
